### ISSUE TITLE
[VC] TODO list for multiple super cluster support

### ISSUE THREAD

**Issue by Fei-Guo** [kubernetes-sigs/multi-tenancy#1377]
The remaining tasks for syncer controller include: 

- [ ] Support selective consistency checks in the patroller based on the tenant namespace placement.
- [ ] Remove the super cluster namespace if the super cluster is removed from the tenant namespace placement.
- [ ] Ensure a tenant Pod can start when its namespace is scheduled in a different root cluster compared to that of the tenant default namespace.

The remaining tasks for the scheduler include:
- [ ] Add tenant resources reconciling logic (for Pod, resource quota, and namespace)
- [ ] Add super cluster resource reconciling logic (for namespace and node)
- [ ] Add basic scheduler framework to support a simple first fit algorithm
- [ ] Support resizing tenant namespace quota
- [ ] Support rescheduling to tolerate super cluster failures
- [ ] Advanced namespace slice scheduling policy (such as affinity) 

@zhuangqh
